### ISSUE TITLE
/dialect doesn't work

### ISSUE THREAD

**Issue by aidabunbun** [Aurorablade/Tongues#10]
when typing /dialect in the chatbox for the command to bring it up, it doesn't do anything. the command doesn't even enter for an error. it just stays in chat and can't enter at all

**Comment by Aurorablade** [comment]
Use /tongues Dialect <dialect> instead. I may have missed the older /Dialect command when I updated

**Comment by aidabunbun** [comment]
that doesn't work either

**Comment by Aurorablade** [comment]
It may be a bit before I can check as I just settled for bed. It may be also a case sesativity issue as my mobile capped the d on dialect

**Comment by aidabunbun** [comment]
tried it capitalized and not and neither work. ty for looking into it when
you can, and sleep well!

**Comment by Aurorablade** [comment]
I am work but something that just occurred to me while on break (still don't look totally) are you on the release or beta build off curse? The beta actually is the latest with some fixes. I should just change it to release.

**Comment by aidabunbun** [comment]
i'm not sure, i just downloaded it from curse. the date on it was 4/27 i
think?

**Comment by Aurorablade** [comment]
Running the older one then it downloaded the release not the beta. Go to files on curse snd download the beta. I will change its type later

**Comment by aidabunbun** [comment]
huh... i switched it over to the beta release and tested both commands and
still nothing. the command enters into chat now, but nothing pops up. not
even an error message

**Comment by Aurorablade** [comment]
okay so when i use '/tongues dialect Gilnean' as a command and type in the word 'what' on my end its comes in as 'wot'  which is correct.
doing '/tongues dialect' with no param resets it to no dialect.
so there is no feedback when it is set from slash command, so this makes me make a major note to self on my next run over (as i am trying to fix the drop downs or sooner) to ADD slash command feedback.
so my apologies there. (half of these commands were me rushing to get it KINDA WORKING while i juggle life and finding a lib i can use for dropdowns that simple enough (i think i got one).

so depending on the dialect you chose you and using the command you will see some words getting replaced but not EVERY word.

**Comment by aidabunbun** [comment]
all good! tysm!! one last question, though. is there a list anywhere of
which dialects there are? or are they the same as the languages?

**Comment by Aurorablade** [comment]
not really but hold on as a reminder some were made with a dropdown in mind, and most just add an affect plus word subsititusions:
Gilnean
Gilnaen-CocknyRhyme    -(Warning some may find it silly)
Dwarvish
Dwarvish(Heavy use with caution)  -((this is how its worded in the code cause it was made with a drop down in mind origanlly))
Draenei
Draenei(Light)
Draenei(Very Light)
Draenei(Heavy)   -(Theres a long story on why theres so many but its ranges from..can understand you to...what..the..f-)
Thalassian
Darnassian
Gnomish
Troll
Troll, Heavy
Taurahe
Orcish
Gutterspeak
Goblin
Heavy Feral
Nerglish
Common, Low
Pirate
Pirate-No Growl

also gonna close this with this comment.
